### ISSUE TITLE
raspberry pi issue

### ISSUE THREAD

**Issue by bvoq** [sony/meta-flutter#60]
I've managed to successfully compile with MACHINE qemuarm64 version but I want to also compile it with MACHINE raspberrypi3.

However, when running the wayland build I get the following strange error. 
It boils down to the folder `/workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter` being empty.

This is the error after running:`build.sh` in https://github.com/bvoq/FlutterMetaDockerfile/tree/main/flutterwaylandrpi3 .
```
NOTE: Executing Tasks
WARNING: flutter-engine-1.0-r0 do_populate_lic: Could not copy license file /workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE to /workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/license-destdir/flutter-engine/LICENSE: [Errno 2] No such file or directory: '/workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE'
ERROR: flutter-engine-1.0-r0 do_populate_lic: QA Issue: flutter-engine: LIC_FILES_CHKSUM points to an invalid file: /workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE [license-checksum]
ERROR: flutter-engine-1.0-r0 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/1.0-r0/temp/log.do_populate_lic.75769
ERROR: Task (/workdir/meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb:do_populate_lic) failed with exit code '1'
```

These are my conf settings: https://github.com/bvoq/FlutterMetaDockerfile/blob/main/flutterwaylandrpi3/wayland_rpi3.sh#L28-L44

**Comment by doesnotexist** [comment]
I get the same error and I'm using meta-meson and MACHINE setting for odroid n2+
I don't really know enough about the moving parts here to know even where to begin debugging this issue.
@HidenoriMatsubayashi  any tips?

**Comment by HidenoriMatsubayashi** [comment]
> raspberrypi3.

Is that target aarch64 or armhf?

**Comment by doesnotexist** [comment]
I think the issue has to do with order in which tasks run in bitbake.  The configure task is running after the populate_lic task and so there is no source available yet to check the LICENSE file's md5sum.  Normally source code would be fetched during the fetch task, however for the flutter-engine recipe, the source code is fetched during the configure task instead because it uses depot_tools  .. Yocto does however support google's repo tool
https://docs.yoctoproject.org/bitbake/bitbake-user-manual/bitbake-user-manual-fetching.html#repo-fetcher-repo
Perhaps fetching the source during the fetch task using google's repo tool would fix the issue?

**Comment by doesnotexist** [comment]
Actually, there's a simpler fix, by just making the ```configure``` task a dependency for the ```populate_lic``` task.

```
do_populate_lic[depends] += "${PN}:do_configure"
```
